INSERT INTO achievement_definitions (
    code,
    name,
    description,
    icon,
    group_name,
    points,
    active,
    auto_unlock_rule,
    rule_type,
    rule_threshold,
    rule_threshold_secondary,
    rule_config_json,
    created_at,
    created_by,
    modified_at,
    modified_by
)
VALUES
    (
        'CUMULATIVE_EXAM_ATTEMPTS_3',
        'Khoi dong thi cu',
        'Hoan thanh 3 bai thi.',
        'FILE_CHECK',
        'Tich luy',
        90,
        TRUE,
        NULL,
        'CUMULATIVE_EXAM_ATTEMPTS',
        3,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'CUMULATIVE_EXAM_ATTEMPTS_10',
        'Ben bi luyen tap',
        'Hoan thanh 10 bai thi.',
        'BOOK_CHECK',
        'Tich luy',
        180,
        TRUE,
        NULL,
        'CUMULATIVE_EXAM_ATTEMPTS',
        10,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'CUMULATIVE_STUDY_MINUTES_60',
        'Nap nang luong',
        'Hoc du 60 phut trong ngay.',
        'CLOCK_3',
        'Tich luy',
        100,
        TRUE,
        NULL,
        'CUMULATIVE_STUDY_MINUTES',
        60,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'CUMULATIVE_STUDY_MINUTES_180',
        'Co may hoc tap',
        'Hoc du 180 phut trong ngay.',
        'TIMER',
        'Tich luy',
        260,
        TRUE,
        NULL,
        'CUMULATIVE_STUDY_MINUTES',
        180,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'STREAK_DAYS_5',
        'Giu nhip hoc',
        'Duy tri streak 5 ngay lien tiep.',
        'FLAME',
        'Chuoi',
        160,
        TRUE,
        NULL,
        'STREAK_DAYS',
        5,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'STREAK_DAYS_14',
        'Ky luat thep',
        'Duy tri streak 14 ngay lien tiep.',
        'TORCH',
        'Chuoi',
        340,
        TRUE,
        NULL,
        'STREAK_DAYS',
        14,
        NULL,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'QUALITY_MIN_SCORE_85_X1',
        'Danh dau xuat sac',
        'Dat tu 85 phan tram it nhat 1 lan.',
        'AWARD',
        'Chat luong',
        150,
        TRUE,
        NULL,
        'QUALITY_MIN_SCORE_ATTEMPTS',
        85,
        1,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'QUALITY_MIN_SCORE_90_X3',
        'Phong do cao',
        'Dat tu 90 phan tram it nhat 3 lan.',
        'CROWN',
        'Chat luong',
        320,
        TRUE,
        NULL,
        'QUALITY_MIN_SCORE_ATTEMPTS',
        90,
        3,
        NULL,
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'COMPOUND_AND_STUDY_SCORE',
        'Toan tam toan luc',
        'Hoc du 120 phut va dat tu 85 phan tram it nhat 1 lan.',
        'SHIELD_CHECK',
        'Ket hop',
        400,
        TRUE,
        NULL,
        'COMPOUND_RULE',
        NULL,
        NULL,
        '{"logic":"AND","clauses":[{"ruleType":"CUMULATIVE_STUDY_MINUTES","threshold":120},{"ruleType":"QUALITY_MIN_SCORE_ATTEMPTS","threshold":85,"thresholdSecondary":1}]}',
        NOW(),
        'system',
        NOW(),
        'system'
    ),
    (
        'COMPOUND_OR_STREAK_QUALITY',
        'Bung no nang luc',
        'Streak tu 10 ngay hoac dat tu 90 phan tram it nhat 2 lan.',
        'SPARKLES',
        'Ket hop',
        420,
        TRUE,
        NULL,
        'COMPOUND_RULE',
        NULL,
        NULL,
        '{"logic":"OR","clauses":[{"ruleType":"STREAK_DAYS","threshold":10},{"ruleType":"QUALITY_MIN_SCORE_ATTEMPTS","threshold":90,"thresholdSecondary":2}]}',
        NOW(),
        'system',
        NOW(),
        'system'
    )
ON CONFLICT (code) DO NOTHING;
